let surahs = [
    "Al-Fatihah The Opener",
    "Al-Baqarah The Cow",
    "Ali Imran Family of Imran",
    "An-Nisa The Women",
    "Al-Maidah The Table Spread",
    "Al-Anam The Cattle",
    "Al-Araf The Heights",
    "Al-Anfal The Spoils of War",
    "At-Tawbah The Repentance",
    "Yunus Jonah",
    "Hud Hud",
    "Yusuf Joseph",
    "Ar-Rad The Thunder",
    "Ibrahim Abrahim",
    "Al-Hijr The Rocky Tract",
    "An-Nahl The Bee",
    "Al-Isra The Night Journey",
    "Al-Kahf The Cave",
    "Maryam Mary",
    "Taha Ta-Ha",
    "Al-Anbya The Prophets",
    "Al-Haj The Pilgrimage",
    "Al-Muminun The Believers",
    "An-Nur The Light",
    "Al-Furqan The Criterian",
    "Ash-Shuara The Poets",
    "An-Naml The Ant",
    "Al-Qasas The Stories",
    "Al-Ankabut The Spider",
    "Ar-Rum The Romans",
    "Luqman Luqman",
    "As-Sajdah The Prostration",
    "Al-Ahzab The Combined Forces",
    "Saba Sheba",
    "Fatir Originator",
    "Ya-Sin Ya Sin",
    "As-Saffat Those who set the Ranks",
    "Sad The Letter Saad",
    "Az-Zumar The Troops",
    "Ghafir The Forgiver",
    "Fussilat Explained in Detail",
    "Ash-Shuraa The Consultation",
    "Az-Zukhruf The Ornaments of Gold",
    "Ad-Dukhan The Smoke",
    "Al-Jathiyah The Crouching",
    "Al-Ahqaf The Wind-Curved Sandhills",
    "Muhammad Muhammad",
    "Al-Fath The Victory",
    "Al-Hujurat The Rooms",
    "Qaf The Letter Qaf",
    "Adh-Dhariyat The Winnowing Winds",
    "At-Tur The Mount",
    "An-Najm The Star",
    "Al-Qamar The Moon",
    "Ar-Rahman The Beneficent",
    "Al-Waqiah The Inevitable",
    "Al-Hadid The Iron",
    "Al-Mujadila The Pleading Woman",
    "Al-Hashr The Exile",
    "Al-Mumtahanah She that is to be examined",
    "As-Saf The Ranks",
    "Al-Jumuah The Congregation, Friday",
    "Al-Munafiqun The Hypocrites",
    "At-Taghabun The Mutual Disillusion",
    "At-Talaq The Divorce",
    "At-Tahrim The Prohibtiion",
    "Al-Mulk The Sovereignty",
    "Al-Qalam The Pen",
    "Al-Haqqah The Reality",
    "Al-Maarij The Ascending Stairways",
    "Nuh Noah",
    "Al-Jinn The Jinn",
    "Al-Muzzammil The Enshrouded One",
    "Al-Muddaththir The Cloaked One",
    "Al-Qiyamah The Resurrection",
    "Al-Insan The Man",
    "Al-Mursalat The Emissaries",
    "An-Naba The Tidings",
    "An-Naziat Those who drag forth",
    "Abasa He Frowned",
    "At-Takwir The Overthrowing",
    "Al-Infitar The Cleaving",
    "Al-Mutaffifin The Defrauding",
    "Al-Inshiqaq The Sundering",
    "Al-Buruj The Mansions of the Stars",
    "At-Tariq The Nightcommer",
    "Al-Ala The Most High",
    "Al-Ghashiyah The Overwhelming",
    "Al-Fajr The Dawn",
    "Al-Balad The City",
    "Ash-Shams The Sun",
    "Al-Layl The Night",
    "Ad-Duhaa The Morning Hours",
    "Ash-Sharh The Relief",
    "At-Tin The Fig",
    "Al-Alaq The Clot",
    "Al-Qadr The Power",
    "Al-Bayyinah The Clear Proof",
    "Az-Zalzalah The Earthquake",
    "Al-Adiyat The Courser",
    "Al-Qariah The Calamity",
    "At-Takathur The Rivalry in world increase",
    "Al-Asr The Declining Day",
    "Al-Humazah The Traducer",
    "Al-Fil The Elephant",
    "Quraysh Quraysh",
    "Al-Maun The Small Kindesses",
    "Al-Kawthar The Abundance",
    "Al-Kafirun The Disbelievers",
    "An-Nasr The Divine Support",
    "Al-Masad The Palm Fiber",
    "Al-Ikhlas The Sincerity",
    "Al-Falaq The Daybreak",
    "An-Nas The Mankind",
  ];

  let Name = "";
 for (let x = 0; x < surahs.length; x++) {
    Name += surahs[x] + "<br>";
  }
  document.getElementById("Names").innerHTML = Name;
